rules:
  dangerous-triggers:
    ignore:
      # this workflow is only triggered after maintainer approval
      - upload_pr_documentation.yml:3:1
  cache-poisoning:
    ignore:
      # the docker buildx binary is cached and zizmor warns about a cache poisoning attack.
      # OTOH this cache would make us more resilient against an intrusion on docker-buildx' side.
      # There is no obvious benefit so we leave it as it is.
      - build_docker_images.yml:35:9
      - build_docker_images.yml:68:9
      - build_docker_images.yml:101:9
      - build_docker_images.yml:134:9
      - build_docker_images.yml:167:9
