name: "\U0001F41B Bug Report"
description: Submit a bug report to help us improve the library
body:
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please share your relevant system information with us
      placeholder: peft & accelerate & transformers version, platform, python version, ...
    validations:
      required: true

  - type: textarea
    id: who-can-help
    attributes:
      label: Who can help?
      description: |
        Your issue will be replied to more quickly if you can figure out the right person to tag with @.
        If you know how to use git blame, that is the easiest way, otherwise, here is a rough guide of **who to tag**.

        All issues are read by one of the core maintainers, so if you don't know who to tag, just leave this blank and
        a core maintainer will ping the right person.

        Please tag fewer than 3 people.

        Library: @benjaminbossan @githubnemo

        diffusers integration: @benjaminbossan @sayakpaul

        Documentation: @stevhliu

      placeholder: "@Username ..."

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        Please provide a code sample that reproduces the problem you ran into. It can be a Colab link or just a code snippet.
        Please provide the simplest reproducer as possible so that we can quickly fix the issue. When you paste
        the error message, please include the full traceback.

      placeholder: |
        Reproducer:

  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you would expect to happen."
