name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

permissions: {}

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@7e6bd45ee271b96e75484eeafea1b3e6139cd0c7  # main
    with:
      commit_sha: ${{ github.sha }}
      package: peft
      notebook_folder: peft_docs
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
