name: Build PR Documentation

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_pr_documentation.yml@bc117cfbd874cbf27a80882e4676f4d06f2bb394  # main
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.number }}
      package: peft
