name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

permissions: {}

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@98154fc40f6896c500b4b4aaf7f2757b4f9cb2ad  # main
    with:
      commit_sha: ${{ github.sha }}
      package: peft
      notebook_folder: peft_docs
      custom_container: huggingface/transformers-doc-builder
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
