name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

permissions: {}

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@7ccf6c02dc2e3aea1b07f6668f783b20c3bf407c  # main
    with:
      commit_sha: ${{ github.sha }}
      package: peft
      notebook_folder: peft_docs
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
