name: Upload PR Documentation

on:
  workflow_run:
    workflows: ["Build PR Documentation"]
    types:
      - completed

permissions: {}

jobs:
  build:
    # skip on forks, the secrets used below only exist in the main repo
    if: github.repository == 'huggingface/peft'
    uses: huggingface/doc-builder/.github/workflows/upload_pr_documentation.yml@bc117cfbd874cbf27a80882e4676f4d06f2bb394  # main
    with:
      package_name: peft
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
      comment_bot_token: ${{ secrets.COMMENT_BOT_TOKEN }}
